//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokedexProject8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokedexProject8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POKEDEX PROJECT 8.1.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string PivotFilePage {
            get {
                return ResourceManager.GetString("PivotFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string PivotFilePageFileBlock {
            get {
                return ResourceManager.GetString("PivotFilePageFileBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica File.
        /// </summary>
        public static string PivotFilePageLoadFile {
            get {
                return ResourceManager.GetString("PivotFilePageLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo File.
        /// </summary>
        public static string PivotFilePageNewFile {
            get {
                return ResourceManager.GetString("PivotFilePageNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Recenti.
        /// </summary>
        public static string PivotFilePageRecentFileBlock {
            get {
                return ResourceManager.GetString("PivotFilePageRecentFileBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokédex.
        /// </summary>
        public static string PivotHomePage {
            get {
                return ResourceManager.GetString("PivotHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        public static string PivotInfoPage {
            get {
                return ResourceManager.GetString("PivotInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string PivotSearchPage {
            get {
                return ResourceManager.GetString("PivotSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luoghi.
        /// </summary>
        public static string PivotSearchPageLocation {
            get {
                return ResourceManager.GetString("PivotSearchPageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon.
        /// </summary>
        public static string PivotSearchPagePokedex {
            get {
                return ResourceManager.GetString("PivotSearchPagePokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca su Pokémon per vedere la lista dei Pokémon, su Regioni per vedere tutti i luoghi..
        /// </summary>
        public static string PivotSearchPageWelcome {
            get {
                return ResourceManager.GetString("PivotSearchPageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Pokémon.
        /// </summary>
        public static string PokeListTitle {
            get {
                return ResourceManager.GetString("PokeListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it-IT.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
